### PR TITLE
Dont force source install on Ubuntu 12.04

### PR DESCRIPTION
**Pull request by oxyc**
See https://github.com/geerlingguy/drupal-vm/pull/1043#issuecomment-266140659

### CODE REVIEW

**Comment by oxyc** [comment]
I guess docker and ubuntu 12 doesn't play nice with restarting redis. I'll test this locally and see if it works. I'll also look into why installing from source didn't work for me.

**Comment by geerlingguy** [comment]
@oxyc - Yeah... I think that was exactly why I started getting angry at 12.04 on Docker. There started to be a lot more bugs than passing tests, so I just ditched it for some of my roles.

LTS support ends in a few short months anyways (https://wiki.ubuntu.com/PrecisePangolin/ReleaseManifest), so I'm starting to roll off 'official' support for any new development, and will be happy to finally cut it out of my routine testing.

**Comment by oxyc** [comment]
Testing this locally with Ubuntu 12.04 and PHP 5.6 from ondrej now.

**Comment by oxyc** [comment]
Works.

**Pull request merged**
